name: flutter_shop
description: Flutter shop app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  badges: ^2.0.2
  intl_phone_number_input: ^0.7.0+2
  country_picker: ^2.0.14
  cupertino_icons: ^1.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/

  fonts:
    - family: Lato
      fonts:
       - asset: assets/fonts/Lato-Regular.ttf
         weight: 400
         style: normal
       - asset: assets/fonts/Lato-Bold.ttf
         weight: 700
       - asset: assets/fonts/Lato-Light.ttf
         weight: 300
         style: normal
       - asset: assets/fonts/Lato-LightItalic.ttf
         weight: 300
         style: italic
    - family: Anton
      fonts:
      - asset: assets/fonts/Anton-Regular.ttf
        weight: 400
        style: normal
